# Generated by Django 5.2.8 on 2025-11-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productimage_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
